Error: ./src/app/(app)/[domain]/communication/page.tsx:27:1 Export sendAdminNotification doesn't exist in target module   25 | import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";   26 | import { useParams } from "next/navigation"; > 27 | import { testSmtpConnectionAction, getEmailSettingsAction, sendAdminNotification } from '@/modules/communication/actions';      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   28 |   29 |   30 | async function fetchData<T>(url: string, options?: RequestInit): Promise<T | null> {
The export sendAdminNotification was not found in module [project]/src/modules/communication/actions.ts [app-client] (ecmascript).
Did you mean to import sendEmailAction?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.

    at <unknown> (Error: ./src/app/(app)/[domain]/communication/page.tsx:27:1)
    at Object.getCompilationErrors (file://D:\Syntaxonehrm\node_modules\next\dist\server\dev\hot-reloader-turbopack.js:722:59)
    at DevBundlerService.getCompilationError (file://D:\Syntaxonehrm\node_modules\next\dist\server\lib\dev-bundler-service.js:39:55)
    at DevServer.getCompilationError (file://D:\Syntaxonehrm\node_modules\next\dist\server\dev\next-dev-server.js:643:42)
    at DevServer.findPageComponents (file://D:\Syntaxonehrm\node_modules\next\dist\server\dev\next-dev-server.js:613:43)
    at async DevServer.renderErrorToResponseImpl (file://D:\Syntaxonehrm\node_modules\next\dist\server\base-server.js:2604:26)